env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

    # For rclone with google drive or any cloud! After first commit pushing, login to https://cirrus-ci.com , click top left corner 3 dot menu, click repository(yourname/aosp-builder) > Repository Settings > Secured Variables > enter content of ~/.config/rclone/rclone.conf (from pc where you setup rclone) > ENCRYPT, copy that ENCRYPTED hash
    # ENCRYPTED variables is unique for every repository, so you cant use my one, create you rclone config https://rclone.org/drive/#making-your-own-client-id
    # CHAT_ID and BOT_TOKEN are used by telegram functions. I don't want you to control my bot xD
    rclone_config: "ENCRYPTED[128335ffd3734f06ef43e14627bcc596f71716ff6393d3469144107d2a553993c562a273b26a496f2b7d86cf23c61823]"
    CHAT_ID: "ENCRYPTED[1f7ce6bfefe1225c3c4d61c2cefc296eb24197f6089279cffaa997a7f7069a124d24d6d2d82992c8cc70e831bcb46367]"
    BOT_TOKEN: "ENCRYPTED[9f3fccb6e054c3014eeceb393088b44bd32a101a07a064bec1984f2db5fc629f81002f69fd88fe90bc2b739344608902]"
    
    # Github variables needed so as to be able to clone private repos too without authenticating. Useful for building official roms which have private repos. The first 3 variables needs to be encrypted!! You can hide your email and username by encrypting them too if you want but that's not neccessary.
    id_rsa_pub: "ENCRYPTED[995b5770cff8494e2997459b9beb3ab8519d7fd922bca8f13d1a7621ecbf8869a152bea07fa74dbf23448f57f5ee9377]"
    id_rsa: "ENCRYPTED[7ee27d5c2e41cfd503d8e8788e3bf1bcfdbde309bd10b5534344a48642af2495fe1fc75c0ee8eb63e71c3d631807a295]"
    known_hosts: "ENCRYPTED[d5b1d0084a47032d9e6d9e689b5063f387a507c18465734287bf8e138af11464e6e0870e8b19549404f6f50e44439d12]"
    user_email: "geekfreak.ahoy123@gmail.com"
    user_name: "geekfreak79"

task:
    name: BlissROM # Project name Build 11 with 6gb ccache
    timeout_in: 4h # Otherwise it will timeout at 60m automatically, 120m highest in free account
    container:
      image: apon77/aosp:latest # It has built-in setup environment + repo, aria2, rclone, pigz, username ci, and email ci@ci.ci [You can use your own docker image if you want, or you can use this one too!]
      cpu: 8  # 8 or less cpu for dummy build, 8 cpu for the final build, 8cpu highest for free accounts. Don't try to use more than 8cpu as free user, you may get blocked by ci.
      memory: 32G # So that we can have ram when needed, 32G highest. 4G per CPU you use.
    download_ccache_background_script: # To download ccache in background
      - ./download_ccache # Ccache download script
    sync_script: # To sync sources
      - ./sync # Source sync script
    monitor_background_script: # To monitor ccache and machine status every minute, runs in background
      - ./monitor # Monitor script
    build_script: # Actual build script foreground
      - ./build # Build script to run
    Upload_script: # Upload rom
      - ./upload_final # script to upload
    upload_ccache_script: # Upload ccache to cloud foreground
      - ./upload_ccache # Build script to upload ccache to drive
